image: ghcr.io/siemens/kas/kas:3.2

variables:
  CPU_REQUEST: ""
  DEFAULT_TAG: ""
  # These are needed as the k8s executor doesn't respect the container
  # entrypoint by default
  FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY: 0
  FF_KUBERNETES_HONOR_ENTRYPOINT: 1

stages:
  - prep
  - build

# Common job fragment to get a worker ready
.setup:
  tags:
    - $DEFAULT_TAG
  stage: build
  interruptible: true
  variables:
    KAS_WORK_DIR: $CI_PROJECT_DIR/work
    KAS_REPO_REF_DIR: $CI_BUILDS_DIR/persist/repos
    SSTATE_DIR: $CI_BUILDS_DIR/persist/sstate
    DL_DIR: $CI_BUILDS_DIR/persist/downloads
    BB_LOGCONFIG: $CI_PROJECT_DIR/ci/logging.yml
  before_script:
    - echo KAS_WORK_DIR = $KAS_WORK_DIR
    - echo SSTATE_DIR = $SSTATE_DIR
    - echo DL_DIR = $DL_DIR
    - rm -rf $KAS_WORK_DIR
    - mkdir --verbose --parents $KAS_WORK_DIR $KAS_REPO_REF_DIR $SSTATE_DIR $DL_DIR
    - sudo apt-get update && sudo apt install -y libtinfo5

# Generalised fragment to do a Kas build
.build:
  extends: .setup
  variables:
    KUBERNETES_CPU_REQUEST: $CPU_REQUEST
  script:
    - KASFILES=$(./ci/jobs-to-kas "$CI_JOB_NAME")
    - kas shell --update --force-checkout $KASFILES -c 'cat conf/*.conf'
    - kas build $KASFILES
    - ./ci/check-warnings $KAS_WORK_DIR/build/warnings.log
  artifacts:
    name: "logs"
    when: on_failure
    paths:
      - $CI_PROJECT_DIR/work/build/tmp/work*/**/temp/log.do_*.*

#
# Prep stage, update repositories once
#
update-repos:
  extends: .setup
  stage: prep
  script:
    - flock --verbose --timeout 60 $KAS_REPO_REF_DIR ./ci/update-repos

check-layers:
  extends: .setup
  coverage: '/Coverage: \d+/'
  script:
    - kas shell --update --force-checkout kas/base.yml --command \
      "yocto-check-layer-wrapper $CI_PROJECT_DIR -n --dependency $KAS_WORK_DIR/meta-arm/meta-arm $KAS_WORK_DIR/meta-arm/meta-arm-toolchain"

#
# Build stage, the actual build jobs
#

morello-soc:
  extends: .build

morello-fvp:
  extends: .build
  parallel:
    matrix:
      - TESTING: [testimage]
  tags:
    - x86_64
