header:
  version: 11

distro: poky

defaults:
  repos:
    refspec: kirkstone

repos:
  meta-morello:

  meta-arm:
    url: https://git.yoctoproject.org/meta-arm
    layers:
      meta-arm:
      meta-arm-bsp:
      meta-arm-toolchain:

  poky:
    url: https://git.yoctoproject.org/git/poky
    layers:
      meta:
      meta-poky:

local_conf_header:
  base: |
    CONF_VERSION = "2"
  setup: |
    PACKAGE_CLASSES = "package_ipk"
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks"

machine: unset

target:
  - core-image-minimal
